### ISSUE TITLE
URL endpoints for CIM documents (Moved from geh-api-gateway repo)

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-shared-resources#35]
## Description

A major part of the system is the ability to receive and send data from market actors. The scope is restrict to receive `CIM XML` via the HTTP protocol. The endpoints can be divided into two categories - sending data and downloading data to/from the system.

This feature enable us to perform a test with external parties. The scope for the test is grid operators and it will take place in start Jan. 2022. The endpoints are defined and documented with `RPC` terms - implying that you are invoking / starting a business process in a remote system.

### Sending data to the system

The proposal from market actors is that an endpoint indicates what document it supports receiving. This means that an endpoint name contains `document name` as part of the URL. The benefit from a system perspective is that routing of data can be based on the URL to the destination domain.

Eg.:

- <https://e2e.datahub.dk/cim/requestchangeofsupplier>
- <https://e2e.datahub.dk/cim/accountingpointcharacteristics>

### Download data from the system

The market actors would prefer to have separate `queue` per document group. Document groups could be `Timeseries`, `Masterdata`, `Charges`; 'All' etc.

## Acceptance Criteria

- [x] We validate that the content type header is `Content-Type: application/xml`
- [x] All endpoints is defined as `Method-Type: POST`
- [x] We expose the endpoints for the following RSM messages:
  - https://e2e.datahub.dk/preprod/cim/??
- [x] We forward each request to the respective domains listed below:
  - https://e2e.datahub.dk/preprod/cim/?? -> Team ??
- [x] For each request we will wait for a response from the forwarded domain, and return that to the caller.
- [x] Endpoints are documented in a consistent manner
