### ISSUE TITLE
Protect our B2B endpoints (API Management) - Moved from geh-api-gateway

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-shared-resources#36]
The public endpoints for B2B messages needs to be protected. A request from the market actors is that we find another solution than the current which relies on certificates. We want to have a solution that is considered best practices and can support different use cases (system to system, user authentication etc).

The scope for this feature is to ensure that we are able to perform a test start Jan 2022 with relevant market actors. Market actors would prefer to use OAuth for authentication on the B2B channel. They have been presented with the `Client Credentials Flow` and that is broadly accepted as sufficient.

## Relevant links:
[OAuth - Client Credentials Flow](https://auth0.com/docs/authorization/flows/client-credentials-flow)
[OAuth - Microsoft](https://docs.microsoft.com/en-us/azure/active-directory-b2c/secure-api-management?tabs=app-reg-ga)

## Acceptance Criteria

- [ ] ~~Create Actor Registry (JSON file) with the actors that are participating in the test in February (We will get a list from DH2)~~
- [x] To request any of the B2B endpoints, the identity must be authenticated
- [x] To request any of the B2B endpoints, the identity must be authorized with the correct claim/role
- [x] If the identity is unauthenticated/unauthorized the request will be rejected

**Comment by mknic** [comment]
Outlined accept criteria is solved [here](https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/geh-shared-resources/44)
